coverage:
  ignore:
    - "Travis/Expects/*"
    - "Travis/prep.sh"
    - "Travis/coverage.sh"
    - "Travis/cleanup.sh"
    - "Travis/sleep.sh"
    - "Travis/Config/*"
  status:
    patch: false
  range: 50...75
  round: up
  precision: 2
