coverage:
  ignore:
    - "Travis/Scripts/Expects/*"
    - "Travis/Scripts/sc_prep.sh"
    - "Travis/Scripts/ur_prep.sh"
    - "Travis/Scripts/sc_coverage.sh"
    - "Travis/Scripts/ur_coverage.sh"
    - "Travis/Scripts/cleanup.sh"
    - "Travis/Scripts/sleep.sh"
    - "Travis/Scripts/shfmt.sh"
    - "Travis/Config/*"
  status:
    patch: false
  range: 40...70
  round: up
  precision: 2
