coverage:
  ignore:
    - "Travis/Scripts/Expects/*"
    - "Travis/Scripts/*_prep.sh"
    - "Travis/Scripts/*_coverage.sh"
    - "Travis/Scripts/cleanup.sh"
    - "Travis/Scripts/sleep.sh"
    - "Travis/Scripts/shfmt.sh"
    - "Travis/Config/*"
  status:
    patch: false
  range: 0...100
  round: up
  precision: 2
