language: bash
#branches:
#  except:
#    - develop
sudo: required
addons:
  apt:
    packages:
      - expect
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
jobs:
  include:
    - stage: test
      script:
        - sudo bash ./Travis/prep.sh
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh -h
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh --help
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh -l
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh --list
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh -n
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh --no-prompt
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh -w
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh --webhook
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh -c http
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh --create http
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh -c ping
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh --create ping
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh -c port
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh --create port
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh -c keyword
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh --create keyword
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh -a
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh --alerts
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh -s
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh --stats
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh -i 'travisone'
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh --info 'travistwo'
        - sudo expect ./Travis/delete_expect_short.exp
        - sudo expect ./Travis/delete_expect_long.exp
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh -p all
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh --pause all
        - sudo expect ./Travis/find_expect_short.exp
        - sudo expect ./Travis/find_expect_long.exp
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh -u all
        - sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh --unpause all
        - sudo expect ./Travis/reset_expect_short.exp
        - sudo expect ./Travis/reset_expect_long.exp
        - sudo expect ./Travis/cleanup.exp
after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  rm -rf kcov-master &&
  mkdir -p coverage &&
  kcov coverage sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh &&
  kcov coverage sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh -h &&
  kcov coverage sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh --help &&
  kcov coverage sudo bash ./Travis/travis_uptimerobot_monitor_utility.sh -l &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh --list &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh -n &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh --no-prompt &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh -w &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh --webhook &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh -c http &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh --create http &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh -c ping &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh --create ping &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh -c port &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh --create port &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh -c keyword &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh --create keyword &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh -f &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh --find &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh -a &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh --alerts &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh -s &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh --stats &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh -d all &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh --delete all &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh -i travisone &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh --info travistwo &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh -p all &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh --pause all &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh -u all &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh --unpause all &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh -r all &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh --reset all &&
  bash <(curl -s https://codecov.io/bash)
