language: bash
#branches:
#  except:
#    - develop
sudo: required
addons:
  apt:
    packages:
      - expect
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
jobs:
  include:
    - stage: prep
      script:
        - sudo bash -x ./Travis/prep.sh
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh -h
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh --help
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh -l
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh --list
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh -n
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh --no-prompt
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh -w
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh --webhook
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh -c http
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh --create http
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh -c ping
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh --create ping
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh -c port
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh --create port
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh -c keyword
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh --create keyword
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh -a
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh --alerts
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh -s
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh --stats
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh -i 'travisone'
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh --info 'travistwo'
        - sudo expect ./Travis/delete_expect_short.exp
        - sudo expect ./Travis/delete_expect_long.exp
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh -p all
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh --pause all
        - sudo expect ./Travis/find_expect_short.exp
        - sudo expect ./Travis/find_expect_long.exp
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh -u all
        - sudo bash -x ./Travis/travis_uptimerobot_monitor_utility.sh --unpause all
        - sudo expect ./Travis/reset_expect_short.exp
        - sudo expect ./Travis/reset_expect_long.exp
        - sudo expect ./Travis/cleanup.exp
after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  rm -rf kcov-master &&
  mkdir -p coverage &&
  kcov coverage Travis/travis_uptimerobot_monitor_utility.sh &&
  bash <(curl -s https://codecov.io/bash)
